# inside config/sidekiq.yml
development:
  :concurrency: 5

production:
  :concurrency: 10

:max_retries: 1

:queues:
  - [default, 8]
  - [mailer, 1]

  # - critical
  # - high
  # - default
  # - low

# - critical
# - ["high", 4]
# - ["default", 2]
# - ["low", 1]